name: Dependency Review

on:
  pull_request:
    branches:
      - "*"

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          format: 'table'