name: "first ci/cd workflow"

on:
  push:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        #   cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: install typescript dependencies
        run: npm install typescript

      - name: Build typescript
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/illthizam_dev_sec_ops
          docker build -t $IMAGE_NAME:latest .


      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/illthizam_dev_sec_ops
          # Use branch name as tag, with 'latest' for main branch
          if [ "$BRANCH_NAME" = "main" ]; then
            TAG="latest"
          else
            TAG="$BRANCH_NAME"
          fi
          
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG